# Generated by Django 2.2.2 on 2019-07-13 04:48

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('disability', models.CharField(max_length=50)),
                ('self_help_skill', multiselectfield.db.fields.MultiSelectField(choices=[('Eating', 'Eating'), ('Sleeping', 'Sleeping'), ('Brushing', 'Brushing'), ('Bathing', 'Bathing'), ('ToiletTraining', 'ToiletTraining')], max_length=47, verbose_name='Self Help')),
                ('behavioural_issues', models.CharField(max_length=500, null=True)),
                ('medication_taken', models.CharField(max_length=500, null=True)),
                ('allergy', models.CharField(max_length=500, null=True)),
                ('remarks', models.CharField(max_length=500, null=True)),
                ('admission_no', models.IntegerField(primary_key=True, serialize=False)),
                ('class1', models.CharField(max_length=100)),
                ('class_teacher', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LookUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_type', models.CharField(choices=[('Assessment', 'Assessment'), ('Admission', 'Admission'), ('Payment', 'Payment')], default='Assessment', max_length=15)),
                ('lookup_name', models.CharField(max_length=100)),
                ('lookup_inputvalue', models.CharField(max_length=100)),
                ('lookup_outputvalue', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_fees_set', models.CharField(max_length=100)),
                ('admission_fees_paid', models.CharField(max_length=100)),
                ('monthly_fees_set', models.CharField(max_length=100)),
                ('uniform_fees_set', models.CharField(max_length=100)),
                ('uniform_fees_paid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('student', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('student_birthday', models.DateField(null=True, verbose_name='Date of Birth')),
                ('religion', models.CharField(choices=[('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Sikhism', 'Sikhism'), ('Others', 'Others, Please specify')], max_length=15, null=True)),
                ('caste', models.CharField(choices=[('general', 'General'), ('obc', 'OBC'), ('sc', 'SC'), ('st', 'ST')], max_length=15, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=15)),
                ('identification_mark', models.CharField(max_length=300, null=True, verbose_name='Identification Marks')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-')], max_length=8, null=True, verbose_name='Blood Group')),
                ('date_of_join', models.DateField(null=True)),
                ('referred_by', models.CharField(max_length=50, null=True, verbose_name='Referred By')),
                ('last_attended_institute_name', models.CharField(max_length=100, null=True, verbose_name='Last attended Institute Name')),
                ('reason_for_leaving', models.CharField(max_length=200, null=True, verbose_name='Reason for leaving')),
                ('disability', models.CharField(max_length=100, null=True)),
                ('disability_percentage', models.CharField(default=10, max_length=5)),
                ('languages_known', models.CharField(max_length=50, verbose_name='Languages Known')),
                ('other_languages_known', models.CharField(blank=True, max_length=50, null=True, verbose_name='Others, Please specify')),
                ('food_preference', models.CharField(choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian')], max_length=15, verbose_name='Food Preference')),
                ('weight', models.IntegerField(null=True, verbose_name='Weight')),
                ('class1', models.CharField(max_length=5, null=True)),
                ('class_teacher', models.CharField(max_length=100)),
                ('attendance', models.IntegerField(null=True)),
                ('height', models.CharField(max_length=5, null=True)),
                ('admission_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentcomponents.Coordinator')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSibling',
            fields=[
                ('sibling', models.AutoField(primary_key=True, serialize=False)),
                ('sibling_name', models.CharField(max_length=50)),
                ('sibling_age', models.IntegerField(null=True)),
                ('sibling_occupation', models.CharField(max_length=12, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentcomponents.StudentDetail')),
            ],
        ),
        migrations.CreateModel(
            name='StudentParent',
            fields=[
                ('student_parent', models.AutoField(primary_key=True, serialize=False)),
                ('parent_name', models.CharField(max_length=50)),
                ('relation_type', models.CharField(choices=[('MOTHER', 'MOTHER'), ('FATHER', 'FATHER'), ('GUARDIAN', 'GUARDIAN')], max_length=15, null=True, verbose_name='Relation type')),
                ('occupation', models.CharField(max_length=12, null=True)),
                ('phone_number', models.CharField(max_length=12, null=True, verbose_name='Phone number')),
                ('email_id', models.EmailField(blank=True, max_length=70, null=True, verbose_name='Email Id')),
                ('address', models.CharField(max_length=300, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentcomponents.StudentDetail')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_sheet', models.FileField(null=True, upload_to='')),
                ('student_picture', models.FileField(null=True, upload_to='')),
                ('gaurdian_picture', models.FileField(null=True, upload_to='')),
                ('adhaar_card_student', models.FileField(null=True, upload_to='')),
                ('adhaar_card_guardian', models.FileField(null=True, upload_to='')),
                ('student_disability_card', models.FileField(null=True, upload_to='')),
                ('student_birth_certificate', models.FileField(null=True, upload_to='')),
                ('student_caste_certificate', models.FileField(null=True, upload_to='')),
                ('student_Niramaya_card', models.FileField(null=True, upload_to='')),
                ('admission_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentcomponents.StudentDetail')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPaidRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_paid_type', models.CharField(choices=[('ADMISSION', 'ADMISSION'), ('UNIFORM', 'UNIFORM'), ('MONTHLY', 'MONTHLY')], max_length=50, verbose_name='Payment Type:')),
                ('fees_paid', models.IntegerField(verbose_name='Fee Amount (in Rs.)')),
                ('fees_paid_date', models.DateField(null=True, verbose_name='Fee Payment Date')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentcomponents.Payment', verbose_name='Student')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentcomponents.StudentDetail'),
        ),
    ]
