# Generated by Django 2.2.2 on 2019-07-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentcomponents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentpaidrecord',
            name='fees_paid_type',
            field=models.CharField(choices=[('', 'Please, payment type'), ('ADMISSION', 'ADMISSION'), ('UNIFORM', 'UNIFORM'), ('MONTHLY', 'MONTHLY')], max_length=50, verbose_name='Payment Type:'),
        ),
    ]
