# Generated by Django 2.2.2 on 2019-07-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentcomponents', '0004_studentdetail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
