# Generated by Django 2.2.2 on 2019-07-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentcomponents', '0005_studentdetail_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='status',
            field=models.CharField(choices=[('CURRENT', 'CURRENT'), ('LEFT', 'LEFT')], default='CURRENT', max_length=100),
        ),
    ]
