# Generated by Django 2.2.1 on 2019-07-19 14:09

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studentcomponents', '0006_auto_20190719_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='self_help_skill',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Eating', 'Eating'), ('Sleeping', 'Sleeping'), ('Brushing', 'Brushing'), ('Bathing', 'Bathing'), ('Toilet Training', 'ToiletTraining')], max_length=48, verbose_name='Self Help'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='caste',
            field=models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='food_preference',
            field=models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian')], max_length=15, verbose_name='Food Preference'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='religion',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
