# Generated by Django 2.2.2 on 2019-07-22 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentcomponents', '0007_auto_20190719_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetail',
            name='other_languages_known',
        ),
    ]
