# Generated by Django 2.2.2 on 2019-08-20 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentcomponents', '0009_auto_20190820_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentpaidrecord',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentcomponents.StudentDetail', verbose_name='Student'),
        ),
    ]
