# Generated by Django 2.2.2 on 2019-08-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentcomponents', '0010_auto_20190820_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='class1',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
