# Generated by Django 2.2.2 on 2019-08-29 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentcomponents', '0011_auto_20190823_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5, null=True)),
                ('admission_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentcomponents.StudentDetail')),
                ('lookup_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentcomponents.LookUp')),
            ],
        ),
    ]
